sudo: required

#define dependencies
services:
  - docker

before_install:
  - docker build -t simple-app/latest
  
  
after_success:
  # Login to docker cli
  - echo "$DOCKER_HUB_PWD" | docker login -u "$DOCKER_HUB_USER" --password-stdin
  # Push the image to docker hub
  - docker push simple-app/latest
 
