sudo: required

#tells travis what language environment to setup (in our case we need go)
language: go

#define dependencies
services:
  - docker

#create the docker image
before_install:
  - docker build -t dorbsz/simple-microservice:latest .

#push the image to docker hub
after_success:
  # Login to docker cli
  - echo "$DOCKER_HUB_PWD" | docker login -u "$DOCKER_HUB_USER" --password-stdin
  # Push the image to docker hub
  - docker push dorbsz/simple-microservice:latest
