version: '3'
services:
  web:
    build: .
    ports:
      - "80:80"
    depends_on:
      - memcached

  memcached:
      image: memcached:alpine
      ports:
        - "11211:11211"
      restart: always
